### ISSUE TITLE
Requirements installation

### ISSUE THREAD

**Issue by Pringmore** [atomic14/ar-browser-sudoku#1]
Thanks for the good job you are doing at first  :+1: 

I have noticed that during the **requirements installation** there are some error messages (incompatibilities) which could be fired on the console due to some used packages with specific versions, such **prompt-toolkit** version, where changing the package version can drive to another version incompatibility!

Just wanted to note that using this command bellow can help to solve part of those incompatibilities.
`# pip install --upgrade pip`
 
It could be added to the README in order to orient users :)

**Comment by cgreening** [comment]
Done
