### ISSUE TITLE
0 Images belonging to 0 Classes  causes an error later

### ISSUE THREAD

**Issue by Pringmore** [atomic14/ar-browser-sudoku#2]
I get the error bellow once I have used the default model **trained.model** by the notebook **test-model**

In order to reproduce this you can fill the folder **all_data/** with some pictures already generated inside for example the folder **training_data/1/* and start running the different section of  the notebook **test-model**.

![image](https://user-images.githubusercontent.com/24613499/91458097-6a4dcf00-e885-11ea-8180-3ef6cdb6ce2d.png)

**Comment by cgreening** [comment]
I'll take a look

**Comment by cgreening** [comment]
I can't recreate this - can you give me a few more details?

It sounds like you're not getting any images from the directory.

What do you see when you run the code block that builds the ImageDataGenerator - you should see something like:

`Found 5193 images belonging to 9 classes.`

**Comment by cgreening** [comment]
I'm going to close this as Stale - please reopen if you are still having problems
